name: Github Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myimage
    - name: build Pages
      run: |
        mkdir _site
        docker run myimage echo "toto" > _site/index.html
        echo "test" > _site/test.html
        cp README.md _site/
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1

