name: Github Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myimage
    - name: build Pages
      run: |
        docker run myimage echo "toto" > index.html

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1

